### ISSUE TITLE
Nodes should have 1 input and 2 outputs

### ISSUE THREAD

**Issue by goliatone** [goliatone/node-red-contrib-bacnet#1]
Read/write nodes should have 1 input to trigger action, and two outputs (one for debug)

```js
this.on('input', (msg)=>{

});
```

**Comment by dopry** [comment]
@goliatone, can you clarify what you're looking for here?  What messages should be passed to output1 and output2?  Generally, when debugging you can connect a single output to multiple downstream nodes. ie) You can connect a single output to both a debug node and the next step in your pipeline.

**Comment by goliatone** [comment]
👍
